site_name: Tdom PyCharm Plugin
site_description: A JetBrains PyCharm plugin for tdom.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 🔗

repo_name: koxudaxi/tdom-pycharm-plugin
repo_url: https://github.com/koxudaxi/tdom-pycharm-plugin
site_url: https://koxudaxi.github.io/tdom-pycharm-plugin

nav:
    - Overview: index.md

plugins:
  - search